#!/usr/bin/perl -w

use strict;

if(open(my $pipe,"grep -P '[0123456789]\s((ch)|(k))olera\si\s' trigrams/* | sort -n -k1.10|")) {
    while(my $line = <$pipe>) {
	print $line;
    }
} else {
    die "Cannot open $pipe: $!";
}
