#!/usr/bin/perl -w

open(my $pipe,"ls yearly/*.text | sort -n |");

print ".PS L\n";

my $prev_lab = 'Week0';
my $counter  = 0;
while(my $file_name = <$pipe>) {
    chomp $file_name;
    my $week = $file_name;
    $week =~ s/^.*\///;
    $week =~ s/.extract//;
    $week =~ s/.text//;

    my $cur_lab = "Week$week";
    if($counter == 0) {
	print "scale=3.0\n";
	print ".po 0.0c\n";
	print ".ps 5\n";
	print ".vs 10\n";
	print 'Y: arrow up 20' . "\n";
	print 'box invis "Cholera i" rjust with .sw at Y.n' . "\n";
	print 'X: arrow right 19 from Y.s' . "\n";
	print 'box invis "Year" with .ne at X.e' . "\n";
	print 'Week0:box invis " " with .n at X.se'."\n";
	$prev_lab = "Week0";
    }
    $counter++;

    print $cur_lab . ':box invis "'.$week.'" wid 1.5 with .sw at ' . $prev_lab  . ".se\n";
    print "sh { sort $file_name | uniq -c | sort -n | tail -45 |perl -ne 's/^\\s+\\d\\s+//;print;'  > " . $file_name . "_shit" . "}\n";
    print "\tcopy \"" . $file_name . "_shit" . '" thru { box invis "$1 $2 $3" ht 0.45   with .s at last box .n}' ."\n";

    $prev_lab = $cur_lab;

}
print ".PE\n";

